CREATE TABLE CUSTOMERS AS SELECT * FROM XSALES.CUSTOMERS;
CREATE TABLE PRODUCTS AS SELECT * FROM XSALES.PRODUCTS;
CREATE TABLE ORDERS AS SELECT * FROM XSALES.ORDERS;
CREATE TABLE ORDER_ITEMS AS SELECT * FROM XSALES.ORDER_ITEMS;

--- A
ALTER TABLE CUSTOMERS
ADD (AGEGROUP VARCHAR2(20));

UPDATE CUSTOMERS
SET
  CUSTOMERS.AGEGROUP = 'under 30'
WHERE 2021- TO_CHAR(BIRTH_DATE,'YYYY') < 30;

UPDATE CUSTOMERS
SET
  CUSTOMERS.AGEGROUP = '30-40'
WHERE 2021- TO_CHAR(BIRTH_DATE,'YYYY') >= 30 and 2021- TO_CHAR(BIRTH_DATE,'YYYY') < 40;

UPDATE CUSTOMERS
SET
  CUSTOMERS.AGEGROUP = '40-50'
WHERE 2021- TO_CHAR(BIRTH_DATE,'YYYY') >= 40 and 2021- TO_CHAR(BIRTH_DATE,'YYYY') < 50;

UPDATE CUSTOMERS
SET
  CUSTOMERS.AGEGROUP = '50-60'
WHERE 2021- TO_CHAR(BIRTH_DATE,'YYYY') >= 50 and 2021- TO_CHAR(BIRTH_DATE,'YYYY') < 60;

UPDATE CUSTOMERS
SET
  CUSTOMERS.AGEGROUP = '60-70'
WHERE 2021- TO_CHAR(BIRTH_DATE,'YYYY') >= 60 and 2021- TO_CHAR(BIRTH_DATE,'YYYY') < 70;

UPDATE CUSTOMERS
SET
  CUSTOMERS.AGEGROUP = 'over 70'
WHERE 2021- TO_CHAR(BIRTH_DATE,'YYYY') >= 70 ;

--- B
select substr(INCOME_LEVEL,1,1) from CUSTOMERS;
ALTER TABLE CUSTOMERS
ADD (INCOME_LEVEL VARCHAR2(20));

UPDATE CUSTOMERS
SET
    CUSTOMERS.INCOME_LEVEL = 'low income'
WHERE substr(INCOME_LEVEL,1,1) = 'A' or substr(INCOME_LEVEL,1,1) = 'B' or substr(INCOME_LEVEL,1,1) = 'C'
or substr(INCOME_LEVEL,1,1) = 'D' OR substr(INCOME_LEVEL,1,1) = 'E';

UPDATE CUSTOMERS
SET
    CUSTOMERS.INCOME_LEVEL = 'medium income'
WHERE substr(INCOME_LEVEL,1,1) = 'F' or substr(INCOME_LEVEL,1,1) = 'G' or substr(INCOME_LEVEL,1,1) = 'H'
or substr(INCOME_LEVEL,1,1) = 'I' OR substr(INCOME_LEVEL,1,1) = 'E';

UPDATE CUSTOMERS
SET
    CUSTOMERS.INCOME_LEVEL = 'high income'
WHERE substr(INCOME_LEVEL,1,1) = 'J' or substr(INCOME_LEVEL,1,1) = 'K' or substr(INCOME_LEVEL,1,1) = 'L';

--- G
UPDATE CUSTOMERS
SET
    MARITAL_STATUS = 'unknown'
WHERE MARITAL_STATUS is null ;

UPDATE CUSTOMERS
SET
    MARITAL_STATUS = 'married'
WHERE MARITAL_STATUS = 'Married' or MARITAL_STATUS = 'Mabsent' or MARITAL_STATUS = 'married' or
      MARITAL_STATUS = 'Married' or MARITAL_STATUS = 'Mar-AF' ;

UPDATE CUSTOMERS
SET
    MARITAL_STATUS = 'Single'
where MARITAL_STATUS = 'NeverM' or MARITAL_STATUS = 'single' or MARITAL_STATUS = 'Separ.' or
      MARITAL_STATUS ='Divorc.' or MARITAL_STATUS = 'Widowed' or MARITAL_STATUS='widow';

--Table alter
ALTER TABLE CUSTOMERS
RENAME COLUMN ID TO Customer_ID;
ALTER TABLE CUSTOMERS
DROP (NAME,BIRTH_DATE,CREDIT_LIMIT,USER_CREATED,DATE_CREATED,USER_MODIFIED,DATE_MODIFIED,EMAIL);

select * from CUSTOMERS;



